# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql-huadan
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: huadan@123
    volumes:
      - ./data:/var/lib/mysql
      - ./init:/init