# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./myql:/var/lib/mysql

  adminer:
    image: adminer
    container_name: sql_web
    restart: always
    ports:
      - 10000:8080