# Use root/example as user/password credentials
version: '3.1'

services:
  redis:
    image: redis
    container_name: redis
    restart: always
    command: redis-server /data/redis.conf
    ports:
      - "6379:6379"
    volumes:
      - ./redis/:/data/
      - ./redis/redis.conf:/data/redis.conf